# Generated by Django 3.2 on 2021-06-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('birth', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Product_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=128)),
                ('img_dir', models.CharField(max_length=128)),
                ('rank', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Search_history',
            fields=[
                ('seq', models.BigIntegerField(primary_key=True, serialize=False)),
                ('member_id', models.CharField(max_length=128)),
                ('search_hst', models.DateTimeField(auto_now_add=True)),
                ('product', models.CharField(max_length=128)),
                ('grade', models.IntegerField()),
            ],
        ),
    ]
