# Generated by Django 3.2.3 on 2021-05-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Search_history',
            fields=[
                ('seq', models.BigIntegerField(primary_key=True, serialize=False)),
                ('member_id', models.CharField(max_length=128)),
                ('search_hst', models.DateTimeField(auto_now_add=True)),
                ('product', models.CharField(max_length=128)),
                ('grade', models.IntegerField()),
            ],
        ),
    ]
