# Generated by Django 3.2.3 on 2021-05-25 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_member_info_product_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
